name: Build and Deploy Snowflake + Pytz Layer with Docker

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Lambda Layer in Docker
        run: |
          docker build -t snowflake-pytz-layer-builder .
          docker run --name snowflake-pytz-builder snowflake-pytz-layer-builder
          docker cp snowflake-pytz-builder:/opt/snowflake-pytz-docker-layer.zip ./snowflake-pytz-docker-layer.zip
          docker rm snowflake-pytz-builder

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Publish Lambda Layer
        run: |
          aws lambda publish-layer-version \
            --layer-name snowflake-pytz-docker-layer \
            --zip-file fileb://snowflake-pytz-docker-layer.zip \
            --compatible-runtimes python3.11 \
            --architecture x86_64 \
            --description "Lambda layer built with Docker containing snowflake-connector and pytz"