name: Upload Lambda Layer (prebuilt locally)

on:
  workflow_dispatch:

jobs:
  upload-layer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload prebuilt snowflake-pytz Layer
        run: |
          aws lambda publish-layer-version \
            --layer-name snowflake-pytz-docker-layer \
            --zip-file fileb://snowflake-pytz-docker-layer.zip \
            --compatible-runtimes python3.11 \
            --architecture x86_64 \
            --description "Lambda layer built locally with Docker containing snowflake-connector and pytz"